### ISSUE TITLE
Why the trace size the same?

### ISSUE THREAD

**Issue by BlackLuny** [ionescu007/winipt#3]
The picture shows in the Readme.You get the trace twice, the size is the same?Why the same size?And how can i make sure that i can get all the trace data,if the buffer is full?How the ipt server works?Could you introduce more detail?Tks.

**Comment by crackzhazha** [comment]
I want to know does ipt.sys support ip range fiters, i did not see this function in you project. Does ipt.sys support? Or u did not complete this function on your tool? I would like help to complete this function if possible!  Tks

**Comment by ionescu007** [comment]
Hi,

Please open new issues instead of re-using the same one in the future.

IP Range filters are not supported by the functionality that Ipt.sys exposes, sorry. There is nothing the tool can do about this.

BlackLuny: The trace size rolls over once the buffer is full, so it never changes. This is normal IPT behavior (please see the manual). Unfortunately, the only way to know that you got all of the data is to keep pulling and use the 'offset' field to know how far along in the trace you've gone. Choosing a bigger trace file will avoid rollovers. Hope this helps.
